// <auto-generated />
using System;
using AnbarUchotu.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace AnbarUchotu.Migrations
{
    [DbContext(typeof(AnbarUchotuDbContext))]
    [Migration("20200310195040_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.1");

            modelBuilder.Entity("AnbarUchotu.Models.Product", b =>
                {
                    b.Property<string>("Guid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Barcode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Count")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT")
                        .HasMaxLength(250);

                    b.Property<decimal>("Mass")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasMaxLength(50);

                    b.Property<decimal>("Price")
                        .HasColumnType("TEXT");

                    b.HasKey("Guid");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("AnbarUchotu.Models.SoldProduct", b =>
                {
                    b.Property<string>("Guid")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProductGuid")
                        .HasColumnType("TEXT");

                    b.Property<int>("SoldCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TransactionGuid")
                        .HasColumnType("TEXT");

                    b.HasKey("Guid");

                    b.HasIndex("ProductGuid");

                    b.HasIndex("TransactionGuid");

                    b.ToTable("SoldProducts");
                });

            modelBuilder.Entity("AnbarUchotu.Models.Transaction", b =>
                {
                    b.Property<string>("Guid")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Amount")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ApprovalDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CancellationDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("IssueDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("IssuerGuid")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.HasKey("Guid");

                    b.HasIndex("IssuerGuid");

                    b.ToTable("Transactions");
                });

            modelBuilder.Entity("AnbarUchotu.Models.User", b =>
                {
                    b.Property<string>("Guid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedEmail")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedUsername")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasMaxLength(50);

                    b.Property<byte[]>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<int>("Role")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasMaxLength(50);

                    b.HasKey("Guid");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("AnbarUchotu.Models.SoldProduct", b =>
                {
                    b.HasOne("AnbarUchotu.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductGuid");

                    b.HasOne("AnbarUchotu.Models.Transaction", "Transaction")
                        .WithMany("Content")
                        .HasForeignKey("TransactionGuid")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("AnbarUchotu.Models.Transaction", b =>
                {
                    b.HasOne("AnbarUchotu.Models.User", "Issuer")
                        .WithMany()
                        .HasForeignKey("IssuerGuid");
                });
#pragma warning restore 612, 618
        }
    }
}
