// <auto-generated />
using System;
using AnbarUchotu.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace AnbarUchotu.Migrations
{
    [DbContext(typeof(AnbarUchotuDbContext))]
    partial class AnbarUchotuDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.1");

            modelBuilder.Entity("AnbarUchotu.Models.BankCard", b =>
                {
                    b.Property<string>("Guid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("AcceptedTransactionsCount")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Balance")
                        .HasColumnType("TEXT");

                    b.Property<string>("CardNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("IssuedTransactionsCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("OwnerGuid")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TotalCancelled")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TotalExpense")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TotalIncome")
                        .HasColumnType("TEXT");

                    b.HasKey("Guid");

                    b.ToTable("BankCards");
                });

            modelBuilder.Entity("AnbarUchotu.Models.Product", b =>
                {
                    b.Property<string>("Guid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Barcode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Count")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT")
                        .HasMaxLength(250);

                    b.Property<decimal>("Mass")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasMaxLength(50);

                    b.Property<string>("OwnerGuid")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasColumnType("TEXT");

                    b.HasKey("Guid");

                    b.HasIndex("OwnerGuid");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("AnbarUchotu.Models.SoldProduct", b =>
                {
                    b.Property<string>("Guid")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProductGuid")
                        .HasColumnType("TEXT");

                    b.Property<int>("SoldCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TransactionGuid")
                        .HasColumnType("TEXT");

                    b.HasKey("Guid");

                    b.HasIndex("ProductGuid");

                    b.HasIndex("TransactionGuid");

                    b.ToTable("SoldProducts");
                });

            modelBuilder.Entity("AnbarUchotu.Models.Transaction", b =>
                {
                    b.Property<string>("Guid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("AcceptorGuid")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Amount")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ApprovalDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CancellationDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("IssueDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("IssuerGuid")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.HasKey("Guid");

                    b.HasIndex("AcceptorGuid");

                    b.HasIndex("IssuerGuid");

                    b.ToTable("Transactions");
                });

            modelBuilder.Entity("AnbarUchotu.Models.User", b =>
                {
                    b.Property<string>("Guid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("CardGuid")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedEmail")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedUsername")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasMaxLength(50);

                    b.Property<byte[]>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<int>("Role")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasMaxLength(50);

                    b.HasKey("Guid");

                    b.HasIndex("CardGuid")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("AnbarUchotu.Models.Product", b =>
                {
                    b.HasOne("AnbarUchotu.Models.User", "Owner")
                        .WithMany()
                        .HasForeignKey("OwnerGuid");
                });

            modelBuilder.Entity("AnbarUchotu.Models.SoldProduct", b =>
                {
                    b.HasOne("AnbarUchotu.Models.Product", "Product")
                        .WithMany("SoldProducts")
                        .HasForeignKey("ProductGuid")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("AnbarUchotu.Models.Transaction", "Transaction")
                        .WithMany("Content")
                        .HasForeignKey("TransactionGuid")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("AnbarUchotu.Models.Transaction", b =>
                {
                    b.HasOne("AnbarUchotu.Models.BankCard", "Acceptor")
                        .WithMany("AcceptedTransactions")
                        .HasForeignKey("AcceptorGuid")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("AnbarUchotu.Models.BankCard", "Issuer")
                        .WithMany("IssuedTransactions")
                        .HasForeignKey("IssuerGuid")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("AnbarUchotu.Models.User", b =>
                {
                    b.HasOne("AnbarUchotu.Models.BankCard", "Card")
                        .WithOne("Owner")
                        .HasForeignKey("AnbarUchotu.Models.User", "CardGuid")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
